name: Deploy To Render


on:
  pull_request:
    branches:
      - deploy
      - main
    types: 
      - closed

  push:
    branches:
      - main


jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  

      - name: Install Dependencies and Run Tests
        run: |
          npm install
          npm run test-component

  deploy:
    if: github.event.pull_request.merged == true  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 

      - name: Deploy to Render
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }} 
        run: |
          curl "$DEPLOY_URL"  # Trigger deployment to Render
          echo "Deployed to Render"
